-- Deploy schemas/ast_constants/procedures/constants to pg

-- requires: schemas/ast_constants/schema

-- NOTE: generated from github.com:pyramation/ast-meta-gen.git

BEGIN;

CREATE FUNCTION ast_constants.role_spec_type ( val text ) RETURNS int AS $EOFCODE$
SELECT CASE
 WHEN ((val) = ('ROLESPEC_CSTRING')) THEN 0
 WHEN ((val) = ('ROLESPEC_CURRENT_USER')) THEN 1
 WHEN ((val) = ('ROLESPEC_SESSION_USER')) THEN 2
 WHEN ((val) = ('ROLESPEC_PUBLIC')) THEN 3 END;
$EOFCODE$ LANGUAGE sql IMMUTABLE;

CREATE FUNCTION ast_constants.sql_value_function_op ( val text ) RETURNS int AS $EOFCODE$
SELECT CASE
 WHEN ((val) = ('SVFOP_CURRENT_DATE')) THEN 0
 WHEN ((val) = ('SVFOP_CURRENT_TIME')) THEN 1
 WHEN ((val) = ('SVFOP_CURRENT_TIME_N')) THEN 2
 WHEN ((val) = ('SVFOP_CURRENT_TIMESTAMP')) THEN 3
 WHEN ((val) = ('SVFOP_CURRENT_TIMESTAMP_N')) THEN 4
 WHEN ((val) = ('SVFOP_LOCALTIME')) THEN 5
 WHEN ((val) = ('SVFOP_LOCALTIME_N')) THEN 6
 WHEN ((val) = ('SVFOP_LOCALTIMESTAMP')) THEN 7
 WHEN ((val) = ('SVFOP_LOCALTIMESTAMP_N')) THEN 8
 WHEN ((val) = ('SVFOP_CURRENT_ROLE')) THEN 9
 WHEN ((val) = ('SVFOP_CURRENT_USER')) THEN 10
 WHEN ((val) = ('SVFOP_USER')) THEN 11
 WHEN ((val) = ('SVFOP_SESSION_USER')) THEN 12
 WHEN ((val) = ('SVFOP_CURRENT_CATALOG')) THEN 13
 WHEN ((val) = ('SVFOP_CURRENT_SCHEMA')) THEN 14 END;
$EOFCODE$ LANGUAGE sql IMMUTABLE;

CREATE FUNCTION ast_constants.bool_expr_type ( val text ) RETURNS int AS $EOFCODE$
SELECT CASE
 WHEN ((val) = ('AND_EXPR')) THEN 0
 WHEN ((val) = ('OR_EXPR')) THEN 1 END;
$EOFCODE$ LANGUAGE sql IMMUTABLE;

CREATE FUNCTION ast_constants.a_expr_kind ( val text ) RETURNS int AS $EOFCODE$
SELECT CASE
 WHEN ((val) = ('AEXPR_OP')) THEN 0
 WHEN ((val) = ('AEXPR_OP_ANY')) THEN 1
 WHEN ((val) = ('AEXPR_OP_ALL')) THEN 2
 WHEN ((val) = ('AEXPR_DISTINCT')) THEN 3
 WHEN ((val) = ('AEXPR_NOT_DISTINCT')) THEN 4
 WHEN ((val) = ('AEXPR_NULLIF')) THEN 5
 WHEN ((val) = ('AEXPR_OF')) THEN 6
 WHEN ((val) = ('AEXPR_IN')) THEN 7
 WHEN ((val) = ('AEXPR_LIKE')) THEN 8
 WHEN ((val) = ('AEXPR_ILIKE')) THEN 9
 WHEN ((val) = ('AEXPR_SIMILAR')) THEN 10
 WHEN ((val) = ('AEXPR_BETWEEN')) THEN 11
 WHEN ((val) = ('AEXPR_NOT_BETWEEN')) THEN 12
 WHEN ((val) = ('AEXPR_BETWEEN_SYM')) THEN 13
 WHEN ((val) = ('AEXPR_NOT_BETWEEN_SYM')) THEN 14
 WHEN ((val) = ('AEXPR_PAREN')) THEN 15 END;
$EOFCODE$ LANGUAGE sql IMMUTABLE;

CREATE FUNCTION ast_constants.null_test_type ( val text ) RETURNS int AS $EOFCODE$
SELECT CASE
 WHEN ((val) = ('IS_NULL')) THEN 0
 WHEN ((val) = ('IS_NOT_NULL')) THEN 1 END;
$EOFCODE$ LANGUAGE sql IMMUTABLE;

CREATE FUNCTION ast_constants.lock_clause_strength ( val text ) RETURNS int AS $EOFCODE$
SELECT CASE
 WHEN ((val) = ('LCS_NONE')) THEN 0
 WHEN ((val) = ('LCS_FORKEYSHARE')) THEN 1
 WHEN ((val) = ('LCS_FORSHARE')) THEN 2
 WHEN ((val) = ('LCS_FORNOKEYUPDATE')) THEN 3
 WHEN ((val) = ('LCS_FORUPDATE')) THEN 4 END;
$EOFCODE$ LANGUAGE sql IMMUTABLE;

CREATE FUNCTION ast_constants.sort_by_dir ( val text ) RETURNS int AS $EOFCODE$
SELECT CASE
 WHEN ((val) = ('SORTBY_DEFAULT')) THEN 0
 WHEN ((val) = ('SORTBY_ASC')) THEN 1
 WHEN ((val) = ('SORTBY_DESC')) THEN 2
 WHEN ((val) = ('SORTBY_USING')) THEN 3 END;
$EOFCODE$ LANGUAGE sql IMMUTABLE;

CREATE FUNCTION ast_constants.sort_by_nulls ( val text ) RETURNS int AS $EOFCODE$
SELECT CASE
 WHEN ((val) = ('SORTBY_NULLS_DEFAULT')) THEN 0
 WHEN ((val) = ('SORTBY_NULLS_FIRST')) THEN 1
 WHEN ((val) = ('SORTBY_NULLS_LAST')) THEN 2 END;
$EOFCODE$ LANGUAGE sql IMMUTABLE;

CREATE FUNCTION ast_constants.variable_set_kind ( val text ) RETURNS int AS $EOFCODE$
SELECT CASE
 WHEN ((val) = ('VAR_SET_VALUE')) THEN 0
 WHEN ((val) = ('VAR_SET_DEFAULT')) THEN 1
 WHEN ((val) = ('VAR_SET_CURRENT')) THEN 2
 WHEN ((val) = ('VAR_SET_MULTI')) THEN 3
 WHEN ((val) = ('VAR_RESET')) THEN 4
 WHEN ((val) = ('VAR_RESET_ALL')) THEN 5 END;
$EOFCODE$ LANGUAGE sql IMMUTABLE;

CREATE FUNCTION ast_constants.object_type ( val text ) RETURNS int AS $EOFCODE$
SELECT CASE
 WHEN ((val) = ('OBJECT_ACCESS_METHOD')) THEN 0
 WHEN ((val) = ('OBJECT_AGGREGATE')) THEN 1
 WHEN ((val) = ('OBJECT_AMOP')) THEN 2
 WHEN ((val) = ('OBJECT_AMPROC')) THEN 3
 WHEN ((val) = ('OBJECT_ATTRIBUTE')) THEN 4
 WHEN ((val) = ('OBJECT_CAST')) THEN 5
 WHEN ((val) = ('OBJECT_COLUMN')) THEN 6
 WHEN ((val) = ('OBJECT_COLLATION')) THEN 7
 WHEN ((val) = ('OBJECT_CONVERSION')) THEN 8
 WHEN ((val) = ('OBJECT_DATABASE')) THEN 9
 WHEN ((val) = ('OBJECT_DEFAULT')) THEN 10
 WHEN ((val) = ('OBJECT_DEFACL')) THEN 11
 WHEN ((val) = ('OBJECT_DOMAIN')) THEN 12
 WHEN ((val) = ('OBJECT_DOMCONSTRAINT')) THEN 13
 WHEN ((val) = ('OBJECT_EVENT_TRIGGER')) THEN 14
 WHEN ((val) = ('OBJECT_EXTENSION')) THEN 15
 WHEN ((val) = ('OBJECT_FDW')) THEN 16
 WHEN ((val) = ('OBJECT_FOREIGN_SERVER')) THEN 17
 WHEN ((val) = ('OBJECT_FOREIGN_TABLE')) THEN 18
 WHEN ((val) = ('OBJECT_FUNCTION')) THEN 19
 WHEN ((val) = ('OBJECT_INDEX')) THEN 20
 WHEN ((val) = ('OBJECT_LANGUAGE')) THEN 21
 WHEN ((val) = ('OBJECT_LARGEOBJECT')) THEN 22
 WHEN ((val) = ('OBJECT_MATVIEW')) THEN 23
 WHEN ((val) = ('OBJECT_OPCLASS')) THEN 24
 WHEN ((val) = ('OBJECT_OPERATOR')) THEN 25
 WHEN ((val) = ('OBJECT_OPFAMILY')) THEN 26
 WHEN ((val) = ('OBJECT_POLICY')) THEN 27
 WHEN ((val) = ('OBJECT_PUBLICATION')) THEN 28
 WHEN ((val) = ('OBJECT_PUBLICATION_REL')) THEN 29
 WHEN ((val) = ('OBJECT_ROLE')) THEN 30
 WHEN ((val) = ('OBJECT_RULE')) THEN 31
 WHEN ((val) = ('OBJECT_SCHEMA')) THEN 32
 WHEN ((val) = ('OBJECT_SEQUENCE')) THEN 33
 WHEN ((val) = ('OBJECT_SUBSCRIPTION')) THEN 34
 WHEN ((val) = ('OBJECT_STATISTIC_EXT')) THEN 35
 WHEN ((val) = ('OBJECT_TABCONSTRAINT')) THEN 36
 WHEN ((val) = ('OBJECT_TABLE')) THEN 37
 WHEN ((val) = ('OBJECT_TABLESPACE')) THEN 38
 WHEN ((val) = ('OBJECT_TRANSFORM')) THEN 39
 WHEN ((val) = ('OBJECT_TRIGGER')) THEN 40
 WHEN ((val) = ('OBJECT_TSCONFIGURATION')) THEN 41
 WHEN ((val) = ('OBJECT_TSDICTIONARY')) THEN 42
 WHEN ((val) = ('OBJECT_TSPARSER')) THEN 43
 WHEN ((val) = ('OBJECT_TSTEMPLATE')) THEN 44
 WHEN ((val) = ('OBJECT_TYPE')) THEN 45
 WHEN ((val) = ('OBJECT_USER_MAPPING')) THEN 46
 WHEN ((val) = ('OBJECT_VIEW')) THEN 47 END;
$EOFCODE$ LANGUAGE sql IMMUTABLE;

CREATE FUNCTION ast_constants.constr_type ( val text ) RETURNS int AS $EOFCODE$
SELECT CASE
 WHEN ((val) = ('CONSTR_NULL')) THEN 0
 WHEN ((val) = ('CONSTR_NOTNULL')) THEN 1
 WHEN ((val) = ('CONSTR_DEFAULT')) THEN 2
 WHEN ((val) = ('CONSTR_IDENTITY')) THEN 3
 WHEN ((val) = ('CONSTR_CHECK')) THEN 4
 WHEN ((val) = ('CONSTR_PRIMARY')) THEN 5
 WHEN ((val) = ('CONSTR_UNIQUE')) THEN 6
 WHEN ((val) = ('CONSTR_EXCLUSION')) THEN 7
 WHEN ((val) = ('CONSTR_FOREIGN')) THEN 8
 WHEN ((val) = ('CONSTR_ATTR_DEFERRABLE')) THEN 9
 WHEN ((val) = ('CONSTR_ATTR_NOT_DEFERRABLE')) THEN 10
 WHEN ((val) = ('CONSTR_ATTR_DEFERRED')) THEN 11
 WHEN ((val) = ('CONSTR_ATTR_IMMEDIATE')) THEN 12 END;
$EOFCODE$ LANGUAGE sql IMMUTABLE;

COMMIT;
